function [ListOfDirs_ALL, ListOfBatch, MotifsToExtract, MotifsToRename, ...
    TargSyl, TargLearnDirs, Date_WNon, Date_SwitchTimes] = ...
    lt_generalization_exptlist(birdname, exptname)

ListOfDirs_ALL = {};
ListOfBatch = {};
MotifsToExtract = {};
MotifsToRename = {};
TargSyl = {};
TargLearnDirs = [];
Date_WNon =  '';
Date_SwitchTimes = {};

%%
if strcmp(birdname, 'wh25pk77') & strcmp(exptname, 'SeqDepPitchLMAN')
    
    % --- PARAMS
    ListOfDirs_ALL = {...
        '/bluejay4/lucas/birds/wh25pk77/011316_SeqDepPitchLMAN_pre', ...
        '/bluejay4/lucas/birds/wh25pk77/011416_SeqDepPitchLMAN_pre', ...
        '/bluejay4/lucas/birds/wh25pk77/011716_SeqDepPitchLMAN_pre', ...
        '/bluejay4/lucas/birds/wh25pk77/011916_SeqDepPitchLMAN_durWN_day1', ...
        '/bluejay4/lucas/birds/wh25pk77/012016_SeqDepPitchLMAN_durWN_day2', ...
        '/bluejay4/lucas/birds/wh25pk77/012116_SeqDepPitchLMAN_durWN_day3'};
    
    ListOfBatch = {...
        'BatchPBS.LABELED', ...
        'BatchPBS.LABELED', ...
        'BatchPBS.LABELED', ...
        'BatchPBS.LABELED', ...
        'BatchPBS.LABELED', ...
        'BatchPBS.LABELED', ...
        };
    
    MotifsToExtract = {'jj(k)b', 'jjk(b)', 'jjkb(b)', ...
        '(a)jnhb', 'ajnh(b)', 'ajnhb(b)'};
    MotifsToRename = {};
    TargSyl = {'ajnhb(b)'};
    TargLearnDirs = [1];
    % --- dates
    Date_WNon =  '19Jan2016-0000';
    Date_SwitchTimes = {};
    
    
elseif strcmp(birdname, 'pu11wh87') & strcmp(exptname, 'SeqDepPitchLMAN')
    
    % --- PARAMS
    ListOfDirs_ALL = {...
        '/bluejay5/lucas/birds/pu11wh87/050215_SeqDepPitch_LMANprobe_PBS_day5', ...
        '/bluejay5/lucas/birds/pu11wh87/050615_SeqDepPitchLMAN_PbsMusc', ...
        '/bluejay5/lucas/birds/pu11wh87/051215_SeqDepPitchLMAN_durWN_day1', ...
        '/bluejay5/lucas/birds/pu11wh87/051315_SeqDepPitchLMAN_durWN_day2', ...
        '/bluejay5/lucas/birds/pu11wh87/051415_SeqDepPitchLMAN_durWN_day3', ...
        '/bluejay5/lucas/birds/pu11wh87/051515_SeqDepPitchLMAN_durWN_day4', ...
        '/bluejay5/lucas/birds/pu11wh87/051615_SeqDepPitchLMAN_durWN_day5'};
    
    ListOfBatch = {...
        'BatchPBS.LABELED', ...
        'BatchPBS.LABELED', ...
        'BatchPBS.LABELED', ...
        'BatchPBS.LABELED', ...
        'BatchPBS.LABELED', ...
        'BatchPBS.LABELED', ...
        'BatchPBS.LABELED', ...
        };
    
    MotifsToExtract = {'(d)ccbb', 'd(c)cbb', 'dc(c)bb', 'dcc(b)b', 'dccb(b)' ...
        '(a)bbccb', 'a(b)bccb', 'ab(b)ccb', 'abb(c)cb', 'abbc(c)b', 'abbcc(b)'};
    MotifsToRename = {};
    TargSyl = {'abbcc(b)'};
    TargLearnDirs = [-1];
    % --- dates
    Date_WNon =  '12May2015-0000';
    Date_SwitchTimes = {};
    
    
elseif strcmp(birdname, 'pu11wh87') & strcmp(exptname, 'SeqDepPitchShift2')
    
    % --- PARAMS
    ListOfDirs_ALL = {...
        '/bluejay5/lucas/birds/pu11wh87/112014_SeqDepPitchShift2_pre', ...
        '/bluejay5/lucas/birds/pu11wh87/112114_SeqDepPitchShift2_pre', ...
        '/bluejay5/lucas/birds/pu11wh87/112214_SeqDepPitchShift2_pre', ...
        '/bluejay5/lucas/birds/pu11wh87/112314_SeqDepPitchShift2_durWN_day1', ...
        '/bluejay5/lucas/birds/pu11wh87/112414_SeqDepPitchShift2_durWN_day2', ...
        '/bluejay5/lucas/birds/pu11wh87/112514_SeqDepPitchShift2_durWN_day3'};
    
    ListOfBatch = {...
        'BatchAll.LABELED', ...
        'BatchAll.LABELED', ...
        'BatchAll.LABELED', ...
        'BatchAll.LABELED', ...
        'BatchAll.LABELED', ...
        'BatchAll.LABELED', ...
        };
    
    MotifsToExtract = {'(d)ccb', 'd(c)cb', 'dc(c)b', 'dcc(b)', ...
        '(a)bbccb', 'a(b)bccb', 'ab(b)ccb', 'abb(c)cb', 'abbc(c)b', 'abbcc(b)', 'abbccb(b)'};
    MotifsToRename = {};
    TargSyl = {'dcc(b)'};
    TargLearnDirs = [1];
    % --- dates
    Date_WNon =  '23Nov2014-0000';
    Date_SwitchTimes = {};
    
    
    
elseif strcmp(birdname, 'pu53wh88') & strcmp(exptname, 'SeqDepPitchShift3')
    
    %     % --- PARAMS RESTORE TO THIS!!
    %     ListOfDirs_ALL = {...
    %     '/bluejay5/lucas/birds/pu53wh88/021115_SeqDepPitchShift3_pre', ...
    %     '/bluejay5/lucas/birds/pu53wh88/021215_SeqDepPitchShift3_pre', ...
    %     '/bluejay5/lucas/birds/pu53wh88/021615_SeqDepPitchShift3_durWN_day4'};
    %     ListOfBatch = {...
    %         'batch.labeled.all', ...
    %         'batch.labeled.all', ...
    %         'BatchAll'};
    %     MotifsToExtract = {'(a)b', 'a(b)', 'ab(b)', ...
    %         '(a)c', 'a(c)', 'ac(c)', 'c(b)', 'cb(b)'};
    %     MotifsToRename = {};
    %     TargSyl = {'ab(b)'};
    %     TargLearnDirs = [-1];
    %     % --- dates
    %     Date_WNon =  '13Feb2015-0000';
    %     Date_SwitchTimes = {};
    
    % --- PARAMS
    ListOfDirs_ALL = {...
        '/bluejay5/lucas/birds/pu53wh88/021015_SeqDepPitchShift3_pre', ...
        '/bluejay5/lucas/birds/pu53wh88/021115_SeqDepPitchShift3_pre', ...
        '/bluejay5/lucas/birds/pu53wh88/021215_SeqDepPitchShift3_pre', ...
        '/bluejay5/lucas/birds/pu53wh88/021415_SeqDepPitchShift3_durWN_day2', ...
        '/bluejay5/lucas/birds/pu53wh88/021515_SeqDepPitchShift3_durWN_day3', ...
        '/bluejay5/lucas/birds/pu53wh88/021615_SeqDepPitchShift3_durWN_day4'};
    ListOfBatch = {...
        'BatchAll.LABELED', ...
        'BatchAll.LABELED', ...
        'BatchAll.LABELED', ...
        'BatchAll.LABELED', ...
        'BatchAll.LABELED', ...
        'BatchAll.LABELED', ...
        };
    MotifsToExtract = {'(a)bb', 'a(b)b', 'ab(b)', ...
        '(a)c', 'a(c)c', 'ac(c)b', 'c(b)b', 'cb(b)'};
    MotifsToRename = {};
    TargSyl = {'ab(b)'};
    TargLearnDirs = [-1];
    % --- dates
    Date_WNon =  '13Feb2015-0000';
    Date_SwitchTimes = {};
    
 elseif strcmp(birdname, 'pu53wh88') & strcmp(exptname, 'SeqDepPitchShift')
    
    % --- PARAMS
    ListOfDirs_ALL = {...
    '/bluejay5/lucas/birds/pu53wh88/102714_SeqDepPitchShift_pre_day5', ...
    '/bluejay5/lucas/birds/pu53wh88/102814_SeqDepPitchShift_pre_day6', ...
    '/bluejay5/lucas/birds/pu53wh88/102914_SeqDepPitchShift_pre_day7', ...
    '/bluejay5/lucas/birds/pu53wh88/110314_SeqDepPitchShift_durWN_day5', ...
    '/bluejay5/lucas/birds/pu53wh88/110414_SeqDepPitchShift_durWN_day6', ...
    '/bluejay5/lucas/birds/pu53wh88/110514_SeqDepPitchShift_durWN_day7'};
    ListOfBatch = {...
    'BatchAll.LABELED', ...
    'BatchAll.LABELED', ...
    'BatchAll.LABELED', ...
    'BatchAll.LABELED', ...
    'BatchAll.LABELED', ...
    'BatchAll.LABELED', ...
        };
MotifsToExtract = {'(a)b', 'a(b)', ...
    '(a)ccbb', 'a(c)cbb', 'ac(c)bb', 'acc(b)b', 'accb(b)'};
    MotifsToRename = {};
    TargSyl = {'a(b)'};
    TargLearnDirs = [-1];
    % --- datest
    Date_WNon =  '30Oct2014-1000';
    Date_SwitchTimes = {};

    
elseif strcmp(birdname, 'wh6pk36') & strcmp(exptname, 'LMANlearn2')
    
    % --- PARAMS
    ListOfDirs_ALL = {...
        '/bluejay5/lucas/birds/wh6pk36/NEURAL/033017_LMANlearn2'};
    ListOfBatch = {...
        'BatchAll'};
    MotifsToExtract = {'mk(s)d', 'mks(d)', ...
        '(v)bga', 'v(b)ga', 'vbg(a)',...
        'm(n)l', '(c)hb', 'c(h)b', 'ch(b)', 'kl(c)', 'nl(c)'};
    MotifsToRename = {...
        {'(v)bga'}, '(b)_oldv', ...
        {'c(h)b'}, '(b)_oldh', ...
        };
    TargSyl = {'ch(b)'};
    TargLearnDirs = [1];
    % --- dates
    Date_WNon =  '30Mar2017-1123';
    Date_SwitchTimes = {'31Mar2017-1224'};
    
    
elseif strcmp(birdname, 'bu77wh13') & strcmp(exptname, 'LMANlearn1')
    
    % --- PARAMS
    ListOfDirs_ALL = {...
        '/bluejay5/lucas/birds/bu77wh13/NEURAL/020517_LMANlearn1'};
    ListOfBatch = {...
        'BatchAll'};
    MotifsToExtract = {'pj(a)b','pja(b)', ...
        'ij(b)', 'ijb(h)', ...
        'n(k)', 'o(k)', 's(k)'}; % note: removed all syls following target
    MotifsToRename = {...
        {'ijb(h)'}, '(b)_oldh'};
    TargSyl = {'pja(b)'};
    TargLearnDirs = [1];
    % --- dates
    Date_WNon =  '05Feb2017-1718';
    Date_SwitchTimes = {'07Feb2017-1509', '12Feb2017-1309'};
    
    
elseif strcmp(birdname, 'or74bk35') & strcmp(exptname, 'LMANneural2')
    
    % --- PARAMS
    ListOfDirs_ALL = {...
        '/bluejay5/lucas/birds/or74bk35/NEURAL/051217_LMANneural2'};
    ListOfBatch = {...
        'BatchAll'};
    MotifsToExtract = {'ja(b)', 'an(b)', 'h(b)', ...
        'ja(n)', ...
        'm(a)', 'a(a)', 'j(a)'}; % NOTE: could potentially add g (but is after WN, but long gap)
    % COULD potnetially convert n to b (since is samish
    % syl)
    % NOTE: could potentailyl add ba(n) and ba(b) but that is 2 syls
    % after target, so should exclude
    %     MotifsToRename = {};
    MotifsToRename = {...
        {'ja(n)'}, '(b)_oldn', ...
        };
    TargSyl = {'an(b)'};
    TargLearnDirs = [1];
    % --- dates
    Date_WNon =  '12May2017-1616';
    Date_SwitchTimes = {};
    
elseif strcmp(birdname, 'pu69wh78') & strcmp(exptname, 'RALMANlearn1')
    
    % --- PARAMS
    ListOfDirs_ALL = {...
        '/bluejay5/lucas/birds/pu69wh78/NEURAL/110117_RALMANlearn1'};
    ListOfBatch = {...
        'BatchAll'};
    %     MotifsToExtract = {'a(b)', 'j(b)', 'ab(h)', 'jb(h)',  'jbh(h)', '(g)'};
    MotifsToExtract = {'a(b)', 'j(b)', 'jb(h)',  'jbh(h)', '(g)'};
    MotifsToRename = {...
        {'jb(h)'}, '(b)_oldh1', ...
        {'jbh(h)'}, '(b)_oldh2', ...
        };
    %     MotifsToRename = {};
    TargSyl = {'a(b)'};
    TargLearnDirs = [1];
    % --- dates
    Date_WNon =  '01Nov2017-1402';
    Date_SwitchTimes = {'01Nov2017-2045'};
    
    
elseif strcmp(birdname, 'pu69wh78') & strcmp(exptname, 'RAlearn1')
    % NOTE: commented out stuff below are not updated. should update if
    % actualyl want to include this experiment.
    % --- PARAMS
    ListOfDirs_ALL = {...
        '/bluejay5/lucas/birds/pu69wh78/NEURAL/103017_RAlearn1'};
    ListOfBatch = {...
        'BatchAll'};
    %     MotifsToExtract = {'a(b)', 'j(b)', 'ab(h)', 'jb(h)',  'jbh(h)', '(g)'};
    %     MotifsToRename = {};
    %     TargSyl = {'a(b)'};
    %     TargLearnDirs = [1];
    %     % --- dates
    %     Date_WNon =  '01Nov2017-1402';
    %     Date_SwitchTimes = {'01Nov2017-2045'};
    
elseif strcmp(birdname, 'wh44wh39') & strcmp(exptname, 'RALMANlearn2')
    % --- PARAMS
    ListOfDirs_ALL = {...
        '/bluejay5/lucas/birds/wh44wh39/NEURAL/031418_RALMANlearn2'};
    ListOfBatch = {...
        'Batch1139to2028'};
    %     MotifsToExtract = {'c(b)', 'cb(b)', '(d)', '(k)', 'k(c)', 'kc(c)', '(n)', ...
    %         'n(h)', 'nh(h)'};
    MotifsToExtract = {'c(b)', '(d)', '(k)', 'k(c)', 'kc(c)', '(n)', ...
        'n(h)', 'nh(h)'};
    MotifsToRename = {...
        {'c(b)'}, '(b)_targ', ...
        { 'k(c)', 'kc(c)'}, '(c)', ...
        {'n(h)'}, '(b)_oldh1', ...
        {'nh(h)'}, '(b)_oldh2', ...
        }; % this will first rescale as deviation from mean (in hz)
    % and then combine. useful e.g. if diff syl across contexts.
    
    %     TargSyl = {'c(b)', 'cb(b)'};
    TargSyl = {'(b)_targ'};
    TargLearnDirs = [1];
    % --- dates
    Date_WNon =  '14Mar2018-1338';
    Date_SwitchTimes = {};
    
elseif strcmp(birdname, 'wh44wh39') & strcmp(exptname, 'RALMANlearn3')
    % --- PARAMS
    ListOfDirs_ALL = {...
        '/bluejay5/lucas/birds/wh44wh39/NEURAL/032118_RALMANlearn3', ...
        '/bluejay5/lucas/birds/wh44wh39/NEURAL/032418_RALMANlearn3', ...
        '/bluejay5/lucas/birds/wh44wh39/NEURAL/040118_RALMANlearn3_audioonly'};
    ListOfBatch = {...
        'BatchAll', ...
        'BatchAllUNDIR',...
        'BatchAllUNDIR'};
    
    MotifsToExtract = {'c(b)', 'cb(b)', '(k)', 'k(c)', 'kc(c)', '(n)', ...
        'n(h)'};
    MotifsToRename = {...
        {'c(b)'}, '(h)_oldb1', ...
        {'cb(b)'}, '(h)_oldb2', ...
        { 'k(c)', 'kc(c)'}, '(c)', ...
        {'n(h)'}, '(h)_targ', ...
        }; % this will first rescale as deviation from mean (in hz)
    % and then combine. useful e.g. if diff syl across contexts.
    
    %     TargSyl = {'n(h)', 'nh(h)'};
    TargSyl = {'(h)_targ'};
    TargLearnDirs = [1];
    
    % --- dates
    Date_WNon =  '21Mar2018-1215';
    %     Date_SwitchTimes = {'21Mar2018-1314', '21Mar2018-1325', '21Mar2018-2347'};
    Date_SwitchTimes = {'21Mar2018-2347'}; % removed short duration when WN on and off.
end
