function sylbad = lt_neural_QUICK_LearnRemoveBadSyl(bname, ename, swnum, syltoken)
%% tells you whether you should keep a given syl for a given switch, learing
% NOTE: have looked closely at all expts so far for wh44 and pu69
% 

%% syllabels that follow the target (on same motif up to 2+ syls) should be excluded

% @# = NOIASE, base and WN
% @ = NOise, base
% # = NOISE, WN
% ? = potentially salvagable (i.e. only noisy epochs, could remove those)

SylsBad = {...,
    {'pu69wh78', 'RALMANOvernightLearn1', 1, 'aabh(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 1, '(a)ab'}, ... % @#
    {'pu69wh78', 'RALMANOvernightLearn1', 1, 'a(a)b'}, ... % @#
    {'pu69wh78', 'RALMANOvernightLearn1', 1, 'aa(b)'}, ... % @#
    {'pu69wh78', 'RALMANOvernightLearn1', 1, 'j(j)b'}, ... % @#
    {'pu69wh78', 'RALMANOvernightLearn1', 1, 'jj(b)'}, ... % @#
    {'pu69wh78', 'RALMANOvernightLearn1', 1, 'h(g)'}, ... % @#
    {'pu69wh78', 'RALMANOvernightLearn1', 1, 'jjbhh(g)'}, ... % #
    {'pu69wh78', 'RALMANOvernightLearn1', 6, 'aab(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 6, 'aabh(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 6, 'jjb(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 6, 'jjbh(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 7, 'aab(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 7, 'aabh(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 7, 'jjb(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 7, 'jjbh(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 8, 'aab(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 8, 'aabh(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 8, 'jjb(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 8, 'jjbh(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 9, 'aabh(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 9, 'jjbh(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 10, 'aab(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 10, 'aabh(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 10, 'jjb(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 10, 'jjbh(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 11, 'aab(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 11, 'aabh(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 11, 'jjb(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 11, 'jjbh(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 12, 'aabh(h)'}, ...
    {'pu69wh78', 'RALMANOvernightLearn1', 12, 'jjbh(h)'}, ...
    {'pu69wh78', 'RALMANlearn1', 1, '(a)ab'}, ... % @#
    {'pu69wh78', 'RALMANlearn2', 1, '(a)ab'}, ... % @#
    {'pu69wh78', 'RALMANlearn2', 1, 'a(a)b'}, ... % @#
    {'pu69wh78', 'RALMANlearn2', 1, 'j(j)b'}, ... % @#
    {'pu69wh78', 'RALMANlearn2', 1, '(j)jb'}, ... % #
    {'pu69wh78', 'RALMANlearn2', 1, 'jj(b)'}, ... % #
    {'wh44wh39', 'RALMANlearn1', 1, 'dk(c)'}, ... % # [note: is actually not bad, except for ch17. others are sort of bad at around 1704+ (sometimes clack). Easiest is just to remove all c]
    {'wh44wh39', 'RALMANlearn1', 2, 'cb(b)'}, ...
    {'wh44wh39', 'RALMANlearn1', 7, 'cb(b)'}, ...
    {'wh44wh39', 'RALMANlearn1', 8, 'cb(b)'}, ...
    {'wh44wh39', 'RALMANlearn1', 9, 'cb(b)'}, ...
    {'wh44wh39', 'RALMANlearn2', 1, 'dk(c)'}, ... % @#
    {'wh44wh39', 'RALMANlearn2', 1, '(m)d'}, ... % #
    {'wh44wh39', 'RALMANlearn2', 1, '(n)h'}, ... % @#
    {'wh44wh39', 'RALMANlearn2', 1, '(j)n'}, ... % #
    {'wh44wh39', 'RALMANlearn2', 1, '(d)kc'}, ... % #
    {'wh44wh39', 'RALMANlearn3', 1, '(m)d'}, ... % #
    {'wh44wh39', 'RALMANlearn3', 1, '(n)h'}, ... % #
    {'wh44wh39', 'RALMANlearn3', 1, 'dk(c)'}, ... % #
    {'wh44wh39', 'RALMANlearn3', 1, 'dkc(c)'}, ... % #
    {'wh44wh39', 'RALMANlearn3', 1, '(d)kc'}, ... % #
    {'wh44wh39', 'RALMANlearn3', 1, '(j)n'}, ... % #
    {'wh44wh39', 'RALMANlearn3', 1, 'nh(h)'}, ...
    {'wh44wh39', 'RALMANlearn4', 1, '(m)d'}, ... % @
    {'wh44wh39', 'RALMANlearn4', 1, '(d)kc'}, ... % @
    {'wh44wh39', 'RALMANlearn4', 1, 'dk(c)'}, ... % @
    {'wh44wh39', 'RALMANlearn4', 1, '(j)n'}, ... % @
    {'wh44wh39', 'RALMANlearn4', 1, '(n)h'}, ... % @#
    {'wh44wh39', 'RALMANlearn4', 2, 'dkc(c)'}, ...
    {'wh72pk12', 'RALMANLearn3', 7, 'jrb(h)'}, ...
    {'wh72pk12', 'RALMANLearn3', 9, 'jrb(h)'}, ...
    {'wh72pk12', 'RALMANLearn3', 11, 'jrb(h)'}, ...
    {'wh72pk12', 'RALMANLearn4', 1, 'klb(h)'}, ...
    {'wh72pk12', 'RALMANLearn5', 1, 'iob(h)'}, ...
    {'wh72pk12', 'RALMANLearn7', 1, 'klb(h)'}, ...
    {'wh72pk12', 'RALMANLearn7', 1, '(g)'}, ...
    {'wh72pk12', 'RALMANLearn7', 1, '(j)rb'}, ...
    {'wh72pk12', 'RALMANLearn7', 2, 'klb(h)'}, ...
    {'wh72pk12', 'RALMANLearn7', 2, '(g)'}, ...
    {'wh72pk12', 'RALMANLearn7', 2, '(j)rb'}, ...
    {'wh72pk12', 'RALMANLearn8', 1, '(m)k'}, ...
    {'wh72pk12', 'RALMANLearn8', 1, '(j)kl'}, ...
    {'gr48bu5', 'RALMANLearn2', 1, 'ab(h)'}, ...
    {'gr48bu5', 'RALMANLearn2', 1, '(a)j'}, ... % @#
    {'gr48bu5', 'RALMANLearn2', 1, '(r)d'}, ... 
    {'gr48bu5', 'RALMANLearn2', 1, '(a)rd'}, ...% @#
    {'gr48bu5', 'RALMANLearn2', 1, '(a)b'}, ...% @#
    {'gr48bu5', 'RALMANLearn3', 1, 'jb(h)'}, ...
    {'gr48bu5', 'RALMANLearn3', 1, '(a)j'}, ...
    {'gr48bu5', 'RALMANLearn3', 1, '(a)rd'}, ...
    {'gr48bu5', 'RALMANLearn3', 1, '(a)b'}, ... % @#
    {'gr48bu5', 'RALMANLearn4', 1, 'jb(h)'}, ...
    {'gr48bu5', 'RALMANLearn4', 1, '(a)rd'}, ...
    {'gr48bu5', 'RALMANLearn4', 1, '(a)b'}, ...
    {'gr48bu5', 'RALMANLearn4', 1, '(a)j'}, ... % @#
    {'gr48bu5', 'RALMANLearn4', 1, 'a(b)'}, ... % @#
    {'gr48bu5', 'RALMANLearn4', 1, '(r)rd'}, ... % @#
    {'gr48bu5', 'RALMANLearn5', 1, 'ab(h)'}, ...
    {'gr48bu5', 'RALMANLearn5', 1, '(a)j'}, ...
    {'gr48bu5', 'RALMANLearn5', 1, '(j)jbh'}, ...    
    {'gr48bu5', 'RALMANLearn5', 1, '(a)rd'}, ... % @#
    {'gr48bu5', 'RALMANLearn5', 1, '(a)b'}, ... % @#
    {'gr48bu5', 'RALMANLearn5', 1, '(r)rd'}, ... % @#
    {'gr48bu5', 'RALMANLearn5', 1, '(r)d'}, ... % @#
    {'gr48bu5', 'RALMANLearn5', 1, 'r(d)'}, ... % @#
    {'gr48bu5', 'RALMANLearn6', 1, '(r)rd'}, ...
    {'gr48bu5', 'RALMANLearn6', 1, '(r)d'}, ... 
    {'gr48bu5', 'RALMANLearn6', 1, '(a)rd'}, ... % @#
    {'gr48bu5', 'RALMANLearn6', 1, '(a)j'}, ... % @#
    {'gr48bu5', 'RALMANLearn6', 1, '(a)b'}, ... % @#
    {'gr48bu5', 'RALMANLearn6', 1, 'ab(h)'}, ...
    {'gr48bu5', 'RALMANLearn6', 1, 'jb(h)'}, ...
};


%% ========== ask whether the input matches any of the bad syls
sylbad = 0;
for j=1:length(SylsBad)
   tmp1 = strcmp(SylsBad{j}{1}, bname);
   tmp2 = strcmp(SylsBad{j}{2}, ename);
   tmp3 = SylsBad{j}{3}==swnum;
   tmp4 = strcmp(SylsBad{j}{4}, syltoken);
   
   if all([tmp1 tmp2 tmp3 tmp4])
       sylbad=1;
       disp(['BAD SYL: ' bname '-' ename '-sw' num2str(swnum) '-' syltoken]);
       break
   end
end

